### ISSUE TITLE
Does not work.

### ISSUE THREAD

**Issue by exorcist365** [kisonecat/lerminus#3]
I did what the instructions said and even more but I can't get it to work in st even though i have the ligatures patch and JetBrains Mono ligatures are working.

**Comment by kisonecat** [comment]
I also use st, but the ligatures for lerminus are not in a standard place, so I have some custom code for getting the ligatures to work on emacs, but they won't work in say vim in st.

I would like to fix this, but I am not sure how it would go -- this being a bitmap font, I don't think there is any way to encode ligatures.  OTF, for instance, supports them, and that's how harfbuzz is figuring out the ligatures in the st patch.

**Comment by exorcist365** [comment]
So it only works in emacs... Are you planning on making a ttf/otf version?

**Comment by exorcist365** [comment]
@kisonecat

**Comment by kisonecat** [comment]
I'm sorry for not replying sooner -- I know that is frustrating.

I probably won't make a TTF or OTF version... my main reason for using Terminus is to get those crispy bitmaps on my low-DPI display.  I have had a lot of trouble avoiding blurry antialiasing when using truetype, even when those truetype fonts were built from bitmaps.  I'd like to understand how to address that so I could make better use of TTF and OTF.

(In the other direction, it'd be interesting to think about how to bake ligature support into BDF/PCF fonts.  With Pango moving from FreeType to HarfBuzz, the future of BDF/PCF is maybe a bit uncertain.  Is there some standard for including ligature information in BDF?  It might be easier to patch st...)
